// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: precisionlocation.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_precisionlocation_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_precisionlocation_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_precisionlocation_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_precisionlocation_2eproto {
  static const uint32_t offsets[];
};
namespace atakmap {
namespace commoncommo {
namespace protobuf {
namespace v1 {
class PrecisionLocation;
struct PrecisionLocationDefaultTypeInternal;
extern PrecisionLocationDefaultTypeInternal _PrecisionLocation_default_instance_;
}  // namespace v1
}  // namespace protobuf
}  // namespace commoncommo
}  // namespace atakmap
PROTOBUF_NAMESPACE_OPEN
template<> ::atakmap::commoncommo::protobuf::v1::PrecisionLocation* Arena::CreateMaybeMessage<::atakmap::commoncommo::protobuf::v1::PrecisionLocation>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace atakmap {
namespace commoncommo {
namespace protobuf {
namespace v1 {

// ===================================================================

class PrecisionLocation final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:atakmap.commoncommo.protobuf.v1.PrecisionLocation) */ {
 public:
  inline PrecisionLocation() : PrecisionLocation(nullptr) {}
  ~PrecisionLocation() override;
  explicit PROTOBUF_CONSTEXPR PrecisionLocation(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PrecisionLocation(const PrecisionLocation& from);
  PrecisionLocation(PrecisionLocation&& from) noexcept
    : PrecisionLocation() {
    *this = ::std::move(from);
  }

  inline PrecisionLocation& operator=(const PrecisionLocation& from) {
    CopyFrom(from);
    return *this;
  }
  inline PrecisionLocation& operator=(PrecisionLocation&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const PrecisionLocation& default_instance() {
    return *internal_default_instance();
  }
  static inline const PrecisionLocation* internal_default_instance() {
    return reinterpret_cast<const PrecisionLocation*>(
               &_PrecisionLocation_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(PrecisionLocation& a, PrecisionLocation& b) {
    a.Swap(&b);
  }
  inline void Swap(PrecisionLocation* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PrecisionLocation* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PrecisionLocation* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PrecisionLocation>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const PrecisionLocation& from);
  void MergeFrom(const PrecisionLocation& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(PrecisionLocation* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "atakmap.commoncommo.protobuf.v1.PrecisionLocation";
  }
  protected:
  explicit PrecisionLocation(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kGeopointsrcFieldNumber = 1,
    kAltsrcFieldNumber = 2,
  };
  // string geopointsrc = 1;
  void clear_geopointsrc();
  const std::string& geopointsrc() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_geopointsrc(ArgT0&& arg0, ArgT... args);
  std::string* mutable_geopointsrc();
  PROTOBUF_NODISCARD std::string* release_geopointsrc();
  void set_allocated_geopointsrc(std::string* geopointsrc);
  private:
  const std::string& _internal_geopointsrc() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_geopointsrc(const std::string& value);
  std::string* _internal_mutable_geopointsrc();
  public:

  // string altsrc = 2;
  void clear_altsrc();
  const std::string& altsrc() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_altsrc(ArgT0&& arg0, ArgT... args);
  std::string* mutable_altsrc();
  PROTOBUF_NODISCARD std::string* release_altsrc();
  void set_allocated_altsrc(std::string* altsrc);
  private:
  const std::string& _internal_altsrc() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_altsrc(const std::string& value);
  std::string* _internal_mutable_altsrc();
  public:

  // @@protoc_insertion_point(class_scope:atakmap.commoncommo.protobuf.v1.PrecisionLocation)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr geopointsrc_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr altsrc_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_precisionlocation_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// PrecisionLocation

// string geopointsrc = 1;
inline void PrecisionLocation::clear_geopointsrc() {
  _impl_.geopointsrc_.ClearToEmpty();
}
inline const std::string& PrecisionLocation::geopointsrc() const {
  // @@protoc_insertion_point(field_get:atakmap.commoncommo.protobuf.v1.PrecisionLocation.geopointsrc)
  return _internal_geopointsrc();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PrecisionLocation::set_geopointsrc(ArgT0&& arg0, ArgT... args) {
 
 _impl_.geopointsrc_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:atakmap.commoncommo.protobuf.v1.PrecisionLocation.geopointsrc)
}
inline std::string* PrecisionLocation::mutable_geopointsrc() {
  std::string* _s = _internal_mutable_geopointsrc();
  // @@protoc_insertion_point(field_mutable:atakmap.commoncommo.protobuf.v1.PrecisionLocation.geopointsrc)
  return _s;
}
inline const std::string& PrecisionLocation::_internal_geopointsrc() const {
  return _impl_.geopointsrc_.Get();
}
inline void PrecisionLocation::_internal_set_geopointsrc(const std::string& value) {
  
  _impl_.geopointsrc_.Set(value, GetArenaForAllocation());
}
inline std::string* PrecisionLocation::_internal_mutable_geopointsrc() {
  
  return _impl_.geopointsrc_.Mutable(GetArenaForAllocation());
}
inline std::string* PrecisionLocation::release_geopointsrc() {
  // @@protoc_insertion_point(field_release:atakmap.commoncommo.protobuf.v1.PrecisionLocation.geopointsrc)
  return _impl_.geopointsrc_.Release();
}
inline void PrecisionLocation::set_allocated_geopointsrc(std::string* geopointsrc) {
  if (geopointsrc != nullptr) {
    
  } else {
    
  }
  _impl_.geopointsrc_.SetAllocated(geopointsrc, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.geopointsrc_.IsDefault()) {
    _impl_.geopointsrc_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:atakmap.commoncommo.protobuf.v1.PrecisionLocation.geopointsrc)
}

// string altsrc = 2;
inline void PrecisionLocation::clear_altsrc() {
  _impl_.altsrc_.ClearToEmpty();
}
inline const std::string& PrecisionLocation::altsrc() const {
  // @@protoc_insertion_point(field_get:atakmap.commoncommo.protobuf.v1.PrecisionLocation.altsrc)
  return _internal_altsrc();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PrecisionLocation::set_altsrc(ArgT0&& arg0, ArgT... args) {
 
 _impl_.altsrc_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:atakmap.commoncommo.protobuf.v1.PrecisionLocation.altsrc)
}
inline std::string* PrecisionLocation::mutable_altsrc() {
  std::string* _s = _internal_mutable_altsrc();
  // @@protoc_insertion_point(field_mutable:atakmap.commoncommo.protobuf.v1.PrecisionLocation.altsrc)
  return _s;
}
inline const std::string& PrecisionLocation::_internal_altsrc() const {
  return _impl_.altsrc_.Get();
}
inline void PrecisionLocation::_internal_set_altsrc(const std::string& value) {
  
  _impl_.altsrc_.Set(value, GetArenaForAllocation());
}
inline std::string* PrecisionLocation::_internal_mutable_altsrc() {
  
  return _impl_.altsrc_.Mutable(GetArenaForAllocation());
}
inline std::string* PrecisionLocation::release_altsrc() {
  // @@protoc_insertion_point(field_release:atakmap.commoncommo.protobuf.v1.PrecisionLocation.altsrc)
  return _impl_.altsrc_.Release();
}
inline void PrecisionLocation::set_allocated_altsrc(std::string* altsrc) {
  if (altsrc != nullptr) {
    
  } else {
    
  }
  _impl_.altsrc_.SetAllocated(altsrc, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.altsrc_.IsDefault()) {
    _impl_.altsrc_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:atakmap.commoncommo.protobuf.v1.PrecisionLocation.altsrc)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace v1
}  // namespace protobuf
}  // namespace commoncommo
}  // namespace atakmap

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_precisionlocation_2eproto
