// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: takmessage.proto

#include "takmessage.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/io/zero_copy_stream_impl_lite.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace atakmap {
namespace commoncommo {
namespace protobuf {
namespace v1 {
PROTOBUF_CONSTEXPR TakMessage::TakMessage(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.takcontrol_)*/nullptr
  , /*decltype(_impl_.cotevent_)*/nullptr
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct TakMessageDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TakMessageDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~TakMessageDefaultTypeInternal() {}
  union {
    TakMessage _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TakMessageDefaultTypeInternal _TakMessage_default_instance_;
}  // namespace v1
}  // namespace protobuf
}  // namespace commoncommo
}  // namespace atakmap
namespace atakmap {
namespace commoncommo {
namespace protobuf {
namespace v1 {

// ===================================================================

class TakMessage::_Internal {
 public:
  static const ::atakmap::commoncommo::protobuf::v1::TakControl& takcontrol(const TakMessage* msg);
  static const ::atakmap::commoncommo::protobuf::v1::CotEvent& cotevent(const TakMessage* msg);
};

const ::atakmap::commoncommo::protobuf::v1::TakControl&
TakMessage::_Internal::takcontrol(const TakMessage* msg) {
  return *msg->_impl_.takcontrol_;
}
const ::atakmap::commoncommo::protobuf::v1::CotEvent&
TakMessage::_Internal::cotevent(const TakMessage* msg) {
  return *msg->_impl_.cotevent_;
}
void TakMessage::clear_takcontrol() {
  if (GetArenaForAllocation() == nullptr && _impl_.takcontrol_ != nullptr) {
    delete _impl_.takcontrol_;
  }
  _impl_.takcontrol_ = nullptr;
}
void TakMessage::clear_cotevent() {
  if (GetArenaForAllocation() == nullptr && _impl_.cotevent_ != nullptr) {
    delete _impl_.cotevent_;
  }
  _impl_.cotevent_ = nullptr;
}
TakMessage::TakMessage(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:atakmap.commoncommo.protobuf.v1.TakMessage)
}
TakMessage::TakMessage(const TakMessage& from)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite() {
  TakMessage* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.takcontrol_){nullptr}
    , decltype(_impl_.cotevent_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
  if (from._internal_has_takcontrol()) {
    _this->_impl_.takcontrol_ = new ::atakmap::commoncommo::protobuf::v1::TakControl(*from._impl_.takcontrol_);
  }
  if (from._internal_has_cotevent()) {
    _this->_impl_.cotevent_ = new ::atakmap::commoncommo::protobuf::v1::CotEvent(*from._impl_.cotevent_);
  }
  // @@protoc_insertion_point(copy_constructor:atakmap.commoncommo.protobuf.v1.TakMessage)
}

inline void TakMessage::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.takcontrol_){nullptr}
    , decltype(_impl_.cotevent_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

TakMessage::~TakMessage() {
  // @@protoc_insertion_point(destructor:atakmap.commoncommo.protobuf.v1.TakMessage)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<std::string>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void TakMessage::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.takcontrol_;
  if (this != internal_default_instance()) delete _impl_.cotevent_;
}

void TakMessage::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void TakMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:atakmap.commoncommo.protobuf.v1.TakMessage)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && _impl_.takcontrol_ != nullptr) {
    delete _impl_.takcontrol_;
  }
  _impl_.takcontrol_ = nullptr;
  if (GetArenaForAllocation() == nullptr && _impl_.cotevent_ != nullptr) {
    delete _impl_.cotevent_;
  }
  _impl_.cotevent_ = nullptr;
  _internal_metadata_.Clear<std::string>();
}

const char* TakMessage::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .atakmap.commoncommo.protobuf.v1.TakControl takControl = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_takcontrol(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .atakmap.commoncommo.protobuf.v1.CotEvent cotEvent = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_cotevent(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<std::string>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* TakMessage::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:atakmap.commoncommo.protobuf.v1.TakMessage)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .atakmap.commoncommo.protobuf.v1.TakControl takControl = 1;
  if (this->_internal_has_takcontrol()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::takcontrol(this),
        _Internal::takcontrol(this).GetCachedSize(), target, stream);
  }

  // .atakmap.commoncommo.protobuf.v1.CotEvent cotEvent = 2;
  if (this->_internal_has_cotevent()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(2, _Internal::cotevent(this),
        _Internal::cotevent(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).data(),
        static_cast<int>(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:atakmap.commoncommo.protobuf.v1.TakMessage)
  return target;
}

size_t TakMessage::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:atakmap.commoncommo.protobuf.v1.TakMessage)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .atakmap.commoncommo.protobuf.v1.TakControl takControl = 1;
  if (this->_internal_has_takcontrol()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.takcontrol_);
  }

  // .atakmap.commoncommo.protobuf.v1.CotEvent cotEvent = 2;
  if (this->_internal_has_cotevent()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.cotevent_);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    total_size += _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size();
  }
  int cached_size = ::_pbi::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void TakMessage::CheckTypeAndMergeFrom(
    const ::PROTOBUF_NAMESPACE_ID::MessageLite& from) {
  MergeFrom(*::_pbi::DownCast<const TakMessage*>(
      &from));
}

void TakMessage::MergeFrom(const TakMessage& from) {
  TakMessage* const _this = this;
  // @@protoc_insertion_point(class_specific_merge_from_start:atakmap.commoncommo.protobuf.v1.TakMessage)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_takcontrol()) {
    _this->_internal_mutable_takcontrol()->::atakmap::commoncommo::protobuf::v1::TakControl::MergeFrom(
        from._internal_takcontrol());
  }
  if (from._internal_has_cotevent()) {
    _this->_internal_mutable_cotevent()->::atakmap::commoncommo::protobuf::v1::CotEvent::MergeFrom(
        from._internal_cotevent());
  }
  _this->_internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
}

void TakMessage::CopyFrom(const TakMessage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:atakmap.commoncommo.protobuf.v1.TakMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TakMessage::IsInitialized() const {
  return true;
}

void TakMessage::InternalSwap(TakMessage* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(TakMessage, _impl_.cotevent_)
      + sizeof(TakMessage::_impl_.cotevent_)
      - PROTOBUF_FIELD_OFFSET(TakMessage, _impl_.takcontrol_)>(
          reinterpret_cast<char*>(&_impl_.takcontrol_),
          reinterpret_cast<char*>(&other->_impl_.takcontrol_));
}

std::string TakMessage::GetTypeName() const {
  return "atakmap.commoncommo.protobuf.v1.TakMessage";
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace v1
}  // namespace protobuf
}  // namespace commoncommo
}  // namespace atakmap
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::atakmap::commoncommo::protobuf::v1::TakMessage*
Arena::CreateMaybeMessage< ::atakmap::commoncommo::protobuf::v1::TakMessage >(Arena* arena) {
  return Arena::CreateMessageInternal< ::atakmap::commoncommo::protobuf::v1::TakMessage >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
