// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: precisionlocation.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_precisionlocation_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_precisionlocation_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_precisionlocation_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_precisionlocation_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
namespace atakmap {
namespace commoncommo {
namespace protobuf {
namespace v1 {
class PrecisionLocation;
class PrecisionLocationDefaultTypeInternal;
extern PrecisionLocationDefaultTypeInternal _PrecisionLocation_default_instance_;
}  // namespace v1
}  // namespace protobuf
}  // namespace commoncommo
}  // namespace atakmap
PROTOBUF_NAMESPACE_OPEN
template<> ::atakmap::commoncommo::protobuf::v1::PrecisionLocation* Arena::CreateMaybeMessage<::atakmap::commoncommo::protobuf::v1::PrecisionLocation>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace atakmap {
namespace commoncommo {
namespace protobuf {
namespace v1 {

// ===================================================================

class PrecisionLocation PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:atakmap.commoncommo.protobuf.v1.PrecisionLocation) */ {
 public:
  inline PrecisionLocation() : PrecisionLocation(nullptr) {};
  virtual ~PrecisionLocation();

  PrecisionLocation(const PrecisionLocation& from);
  PrecisionLocation(PrecisionLocation&& from) noexcept
    : PrecisionLocation() {
    *this = ::std::move(from);
  }

  inline PrecisionLocation& operator=(const PrecisionLocation& from) {
    CopyFrom(from);
    return *this;
  }
  inline PrecisionLocation& operator=(PrecisionLocation&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const PrecisionLocation& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PrecisionLocation* internal_default_instance() {
    return reinterpret_cast<const PrecisionLocation*>(
               &_PrecisionLocation_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(PrecisionLocation& a, PrecisionLocation& b) {
    a.Swap(&b);
  }
  inline void Swap(PrecisionLocation* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PrecisionLocation* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline PrecisionLocation* New() const final {
    return CreateMaybeMessage<PrecisionLocation>(nullptr);
  }

  PrecisionLocation* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<PrecisionLocation>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)
    final;
  void CopyFrom(const PrecisionLocation& from);
  void MergeFrom(const PrecisionLocation& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  void DiscardUnknownFields();
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(PrecisionLocation* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "atakmap.commoncommo.protobuf.v1.PrecisionLocation";
  }
  protected:
  explicit PrecisionLocation(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kGeopointsrcFieldNumber = 1,
    kAltsrcFieldNumber = 2,
  };
  // string geopointsrc = 1;
  void clear_geopointsrc();
  const std::string& geopointsrc() const;
  void set_geopointsrc(const std::string& value);
  void set_geopointsrc(std::string&& value);
  void set_geopointsrc(const char* value);
  void set_geopointsrc(const char* value, size_t size);
  std::string* mutable_geopointsrc();
  std::string* release_geopointsrc();
  void set_allocated_geopointsrc(std::string* geopointsrc);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_geopointsrc();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_geopointsrc(
      std::string* geopointsrc);
  private:
  const std::string& _internal_geopointsrc() const;
  void _internal_set_geopointsrc(const std::string& value);
  std::string* _internal_mutable_geopointsrc();
  public:

  // string altsrc = 2;
  void clear_altsrc();
  const std::string& altsrc() const;
  void set_altsrc(const std::string& value);
  void set_altsrc(std::string&& value);
  void set_altsrc(const char* value);
  void set_altsrc(const char* value, size_t size);
  std::string* mutable_altsrc();
  std::string* release_altsrc();
  void set_allocated_altsrc(std::string* altsrc);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_altsrc();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_altsrc(
      std::string* altsrc);
  private:
  const std::string& _internal_altsrc() const;
  void _internal_set_altsrc(const std::string& value);
  std::string* _internal_mutable_altsrc();
  public:

  // @@protoc_insertion_point(class_scope:atakmap.commoncommo.protobuf.v1.PrecisionLocation)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr geopointsrc_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr altsrc_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_precisionlocation_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// PrecisionLocation

// string geopointsrc = 1;
inline void PrecisionLocation::clear_geopointsrc() {
  geopointsrc_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& PrecisionLocation::geopointsrc() const {
  // @@protoc_insertion_point(field_get:atakmap.commoncommo.protobuf.v1.PrecisionLocation.geopointsrc)
  return _internal_geopointsrc();
}
inline void PrecisionLocation::set_geopointsrc(const std::string& value) {
  _internal_set_geopointsrc(value);
  // @@protoc_insertion_point(field_set:atakmap.commoncommo.protobuf.v1.PrecisionLocation.geopointsrc)
}
inline std::string* PrecisionLocation::mutable_geopointsrc() {
  // @@protoc_insertion_point(field_mutable:atakmap.commoncommo.protobuf.v1.PrecisionLocation.geopointsrc)
  return _internal_mutable_geopointsrc();
}
inline const std::string& PrecisionLocation::_internal_geopointsrc() const {
  return geopointsrc_.Get();
}
inline void PrecisionLocation::_internal_set_geopointsrc(const std::string& value) {
  
  geopointsrc_.SetLite(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void PrecisionLocation::set_geopointsrc(std::string&& value) {
  
  geopointsrc_.SetLite(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:atakmap.commoncommo.protobuf.v1.PrecisionLocation.geopointsrc)
}
inline void PrecisionLocation::set_geopointsrc(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  geopointsrc_.SetLite(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:atakmap.commoncommo.protobuf.v1.PrecisionLocation.geopointsrc)
}
inline void PrecisionLocation::set_geopointsrc(const char* value,
    size_t size) {
  
  geopointsrc_.SetLite(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:atakmap.commoncommo.protobuf.v1.PrecisionLocation.geopointsrc)
}
inline std::string* PrecisionLocation::_internal_mutable_geopointsrc() {
  
  return geopointsrc_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* PrecisionLocation::release_geopointsrc() {
  // @@protoc_insertion_point(field_release:atakmap.commoncommo.protobuf.v1.PrecisionLocation.geopointsrc)
  return geopointsrc_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void PrecisionLocation::set_allocated_geopointsrc(std::string* geopointsrc) {
  if (geopointsrc != nullptr) {
    
  } else {
    
  }
  geopointsrc_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), geopointsrc,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:atakmap.commoncommo.protobuf.v1.PrecisionLocation.geopointsrc)
}
inline std::string* PrecisionLocation::unsafe_arena_release_geopointsrc() {
  // @@protoc_insertion_point(field_unsafe_arena_release:atakmap.commoncommo.protobuf.v1.PrecisionLocation.geopointsrc)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return geopointsrc_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void PrecisionLocation::unsafe_arena_set_allocated_geopointsrc(
    std::string* geopointsrc) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (geopointsrc != nullptr) {
    
  } else {
    
  }
  geopointsrc_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      geopointsrc, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:atakmap.commoncommo.protobuf.v1.PrecisionLocation.geopointsrc)
}

// string altsrc = 2;
inline void PrecisionLocation::clear_altsrc() {
  altsrc_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& PrecisionLocation::altsrc() const {
  // @@protoc_insertion_point(field_get:atakmap.commoncommo.protobuf.v1.PrecisionLocation.altsrc)
  return _internal_altsrc();
}
inline void PrecisionLocation::set_altsrc(const std::string& value) {
  _internal_set_altsrc(value);
  // @@protoc_insertion_point(field_set:atakmap.commoncommo.protobuf.v1.PrecisionLocation.altsrc)
}
inline std::string* PrecisionLocation::mutable_altsrc() {
  // @@protoc_insertion_point(field_mutable:atakmap.commoncommo.protobuf.v1.PrecisionLocation.altsrc)
  return _internal_mutable_altsrc();
}
inline const std::string& PrecisionLocation::_internal_altsrc() const {
  return altsrc_.Get();
}
inline void PrecisionLocation::_internal_set_altsrc(const std::string& value) {
  
  altsrc_.SetLite(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void PrecisionLocation::set_altsrc(std::string&& value) {
  
  altsrc_.SetLite(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:atakmap.commoncommo.protobuf.v1.PrecisionLocation.altsrc)
}
inline void PrecisionLocation::set_altsrc(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  altsrc_.SetLite(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:atakmap.commoncommo.protobuf.v1.PrecisionLocation.altsrc)
}
inline void PrecisionLocation::set_altsrc(const char* value,
    size_t size) {
  
  altsrc_.SetLite(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:atakmap.commoncommo.protobuf.v1.PrecisionLocation.altsrc)
}
inline std::string* PrecisionLocation::_internal_mutable_altsrc() {
  
  return altsrc_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* PrecisionLocation::release_altsrc() {
  // @@protoc_insertion_point(field_release:atakmap.commoncommo.protobuf.v1.PrecisionLocation.altsrc)
  return altsrc_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void PrecisionLocation::set_allocated_altsrc(std::string* altsrc) {
  if (altsrc != nullptr) {
    
  } else {
    
  }
  altsrc_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), altsrc,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:atakmap.commoncommo.protobuf.v1.PrecisionLocation.altsrc)
}
inline std::string* PrecisionLocation::unsafe_arena_release_altsrc() {
  // @@protoc_insertion_point(field_unsafe_arena_release:atakmap.commoncommo.protobuf.v1.PrecisionLocation.altsrc)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return altsrc_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void PrecisionLocation::unsafe_arena_set_allocated_altsrc(
    std::string* altsrc) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (altsrc != nullptr) {
    
  } else {
    
  }
  altsrc_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      altsrc, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:atakmap.commoncommo.protobuf.v1.PrecisionLocation.altsrc)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace v1
}  // namespace protobuf
}  // namespace commoncommo
}  // namespace atakmap

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_precisionlocation_2eproto
