// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: takcontrol.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_takcontrol_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_takcontrol_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_takcontrol_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_takcontrol_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
namespace atakmap {
namespace commoncommo {
namespace protobuf {
namespace v1 {
class TakControl;
class TakControlDefaultTypeInternal;
extern TakControlDefaultTypeInternal _TakControl_default_instance_;
}  // namespace v1
}  // namespace protobuf
}  // namespace commoncommo
}  // namespace atakmap
PROTOBUF_NAMESPACE_OPEN
template<> ::atakmap::commoncommo::protobuf::v1::TakControl* Arena::CreateMaybeMessage<::atakmap::commoncommo::protobuf::v1::TakControl>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace atakmap {
namespace commoncommo {
namespace protobuf {
namespace v1 {

// ===================================================================

class TakControl PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:atakmap.commoncommo.protobuf.v1.TakControl) */ {
 public:
  inline TakControl() : TakControl(nullptr) {};
  virtual ~TakControl();

  TakControl(const TakControl& from);
  TakControl(TakControl&& from) noexcept
    : TakControl() {
    *this = ::std::move(from);
  }

  inline TakControl& operator=(const TakControl& from) {
    CopyFrom(from);
    return *this;
  }
  inline TakControl& operator=(TakControl&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const TakControl& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const TakControl* internal_default_instance() {
    return reinterpret_cast<const TakControl*>(
               &_TakControl_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(TakControl& a, TakControl& b) {
    a.Swap(&b);
  }
  inline void Swap(TakControl* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TakControl* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline TakControl* New() const final {
    return CreateMaybeMessage<TakControl>(nullptr);
  }

  TakControl* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<TakControl>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)
    final;
  void CopyFrom(const TakControl& from);
  void MergeFrom(const TakControl& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  void DiscardUnknownFields();
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(TakControl* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "atakmap.commoncommo.protobuf.v1.TakControl";
  }
  protected:
  explicit TakControl(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kContactUidFieldNumber = 3,
    kMinProtoVersionFieldNumber = 1,
    kMaxProtoVersionFieldNumber = 2,
  };
  // string contactUid = 3;
  void clear_contactuid();
  const std::string& contactuid() const;
  void set_contactuid(const std::string& value);
  void set_contactuid(std::string&& value);
  void set_contactuid(const char* value);
  void set_contactuid(const char* value, size_t size);
  std::string* mutable_contactuid();
  std::string* release_contactuid();
  void set_allocated_contactuid(std::string* contactuid);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_contactuid();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_contactuid(
      std::string* contactuid);
  private:
  const std::string& _internal_contactuid() const;
  void _internal_set_contactuid(const std::string& value);
  std::string* _internal_mutable_contactuid();
  public:

  // uint32 minProtoVersion = 1;
  void clear_minprotoversion();
  ::PROTOBUF_NAMESPACE_ID::uint32 minprotoversion() const;
  void set_minprotoversion(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_minprotoversion() const;
  void _internal_set_minprotoversion(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // uint32 maxProtoVersion = 2;
  void clear_maxprotoversion();
  ::PROTOBUF_NAMESPACE_ID::uint32 maxprotoversion() const;
  void set_maxprotoversion(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_maxprotoversion() const;
  void _internal_set_maxprotoversion(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // @@protoc_insertion_point(class_scope:atakmap.commoncommo.protobuf.v1.TakControl)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr contactuid_;
  ::PROTOBUF_NAMESPACE_ID::uint32 minprotoversion_;
  ::PROTOBUF_NAMESPACE_ID::uint32 maxprotoversion_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_takcontrol_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// TakControl

// uint32 minProtoVersion = 1;
inline void TakControl::clear_minprotoversion() {
  minprotoversion_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 TakControl::_internal_minprotoversion() const {
  return minprotoversion_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 TakControl::minprotoversion() const {
  // @@protoc_insertion_point(field_get:atakmap.commoncommo.protobuf.v1.TakControl.minProtoVersion)
  return _internal_minprotoversion();
}
inline void TakControl::_internal_set_minprotoversion(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  minprotoversion_ = value;
}
inline void TakControl::set_minprotoversion(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_minprotoversion(value);
  // @@protoc_insertion_point(field_set:atakmap.commoncommo.protobuf.v1.TakControl.minProtoVersion)
}

// uint32 maxProtoVersion = 2;
inline void TakControl::clear_maxprotoversion() {
  maxprotoversion_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 TakControl::_internal_maxprotoversion() const {
  return maxprotoversion_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 TakControl::maxprotoversion() const {
  // @@protoc_insertion_point(field_get:atakmap.commoncommo.protobuf.v1.TakControl.maxProtoVersion)
  return _internal_maxprotoversion();
}
inline void TakControl::_internal_set_maxprotoversion(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  maxprotoversion_ = value;
}
inline void TakControl::set_maxprotoversion(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_maxprotoversion(value);
  // @@protoc_insertion_point(field_set:atakmap.commoncommo.protobuf.v1.TakControl.maxProtoVersion)
}

// string contactUid = 3;
inline void TakControl::clear_contactuid() {
  contactuid_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& TakControl::contactuid() const {
  // @@protoc_insertion_point(field_get:atakmap.commoncommo.protobuf.v1.TakControl.contactUid)
  return _internal_contactuid();
}
inline void TakControl::set_contactuid(const std::string& value) {
  _internal_set_contactuid(value);
  // @@protoc_insertion_point(field_set:atakmap.commoncommo.protobuf.v1.TakControl.contactUid)
}
inline std::string* TakControl::mutable_contactuid() {
  // @@protoc_insertion_point(field_mutable:atakmap.commoncommo.protobuf.v1.TakControl.contactUid)
  return _internal_mutable_contactuid();
}
inline const std::string& TakControl::_internal_contactuid() const {
  return contactuid_.Get();
}
inline void TakControl::_internal_set_contactuid(const std::string& value) {
  
  contactuid_.SetLite(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void TakControl::set_contactuid(std::string&& value) {
  
  contactuid_.SetLite(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:atakmap.commoncommo.protobuf.v1.TakControl.contactUid)
}
inline void TakControl::set_contactuid(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  contactuid_.SetLite(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:atakmap.commoncommo.protobuf.v1.TakControl.contactUid)
}
inline void TakControl::set_contactuid(const char* value,
    size_t size) {
  
  contactuid_.SetLite(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:atakmap.commoncommo.protobuf.v1.TakControl.contactUid)
}
inline std::string* TakControl::_internal_mutable_contactuid() {
  
  return contactuid_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* TakControl::release_contactuid() {
  // @@protoc_insertion_point(field_release:atakmap.commoncommo.protobuf.v1.TakControl.contactUid)
  return contactuid_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void TakControl::set_allocated_contactuid(std::string* contactuid) {
  if (contactuid != nullptr) {
    
  } else {
    
  }
  contactuid_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), contactuid,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:atakmap.commoncommo.protobuf.v1.TakControl.contactUid)
}
inline std::string* TakControl::unsafe_arena_release_contactuid() {
  // @@protoc_insertion_point(field_unsafe_arena_release:atakmap.commoncommo.protobuf.v1.TakControl.contactUid)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return contactuid_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void TakControl::unsafe_arena_set_allocated_contactuid(
    std::string* contactuid) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (contactuid != nullptr) {
    
  } else {
    
  }
  contactuid_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      contactuid, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:atakmap.commoncommo.protobuf.v1.TakControl.contactUid)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace v1
}  // namespace protobuf
}  // namespace commoncommo
}  // namespace atakmap

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_takcontrol_2eproto
